version: "3"
name: pihole
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8654:80/tcp"
    environment:
      TZ: 'Europe/Istanbul'
      WEBPASSWORD: UvePoYvgVf7urG
    volumes:
      - /opt/pihole/data/etc-pihole:/etc/pihole
      - /opt/pihole/data/etc-dnsmasq.d:/etc/dnsmasq.d
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped